Fixed issue https://github.com/Chimpagne/ChimpagneApp/issues/119
Chimpagne/ChimpagneApp pull request #126
Opened 2024-05-01 16:47 UTC by juaniac

This PR is meant to fix issue like the one described here: https://github.com/Chimpagne/ChimpagneApp/issues/119 where the UI view model doesn't update correctly because the view model is being cached and is not fetching the newer information from the database.
The proposed solution here are that now all fetch style functions of view models are made public so that the UI can call them when the screen is created / recreated.

2024-05-01 17:32 UTC, QuicheLorraine3600 requested changes
This is a nice trick, but it doesn't fully solve the problem. With your proposed paradigm, each screen has to call fetchEvent itself at each recomposition. Screen recomposition can happen very often and this will be an issue for #108 as fetchEvent will be called each time the user type something, overriding its changes with the values stored in the database ! 

I propose another solution: the fetch happens in the MainActivity navgraph. This way, the screen writer doesn't have to worry about the potential garbage in the View Model given to him and EditEventScreen won't be broken.

2024-05-01 17:40 UTC, juaniac commented
Indeed that seems to be a more robust solution to the problem. 
Thank you for the proposal.

2024-05-02 08:05 UTC, Athanaze commented
While line coverage is insufficient, this needs to be merged asap for the team to move forward. 

Good job on fixing the issue !🚀

2024-05-02 08:06 UTC, Athanaze approved these changes

2024-05-02 08:08 UTC, QuicheLorraine3600 approved these changes

2024-05-02 08:08 UTC, merged