Social links
Chimpagne/ChimpagneApp pull request #150
Opened 2024-05-05 10:38 UTC by Kuriv2001

Adding the capability to add social links to your event, display them on the detailed event screen and also being able to update them via edit event. (For security reasons no direct links allowed).

Still to be done:

- Tests
- update figma
- finish PR details

2024-05-08 14:37 UTC, QuicheLorraine3600 requested changes
This is a very nice work, but after a small discussion with the team, we have concluded that putting a Instagram and a Discord username per event isn't really what we need.
We want to have urls to Whatsapp or Instagram groups per events to make sure guests and staffs can chat with each other.
The changes required are minimal, you just have to change the placeholder asking for a username to a placeholder asking for an URL.

2024-05-09 06:31 UTC, Kuriv2001 commented
Alright, I changed the fields to be able to take links now, while still making sure they're links to the correct sites and not some random ones (for security). I checked and for whatsapp there are group invite links, for instagram I'm not sure though.

2024-05-09 08:17 UTC, Kuriv2001 commented
On demand and availability of invite links, the selection has been changed to: Discord + Telegram + Whatsapp.

2024-05-10 17:56 UTC, QuicheLorraine3600 requested changes
Nice ! In order to support be able to add social media easily, it would be nice to create a data class representing a `SocialMedia`. Then you could create a `SUPPORTED_SOCIAL_MEDIA: List<SocialMedia>`

2024-05-10 17:56 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt
> +        platformUrl = "https://discord.gg/")
hardcoded link

2024-05-10 17:56 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt
> +        platformName = "discord",
hardcoded name

2024-05-10 17:56 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt
> +        platformUrl = "https://t.me/")
hardcoded link

2024-05-10 17:56 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt
> +        platformName = "telegram",
hardcoded name

2024-05-10 17:56 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt
> +        labelResource = R.string.telegram_group_invite_link,
hardcoded icon

2024-05-10 17:56 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt
> +        platformUrl = "https://chat.whatsapp.com/")
hardcoded link

2024-05-10 17:56 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEvent.kt
> +        mapOf("discord" to "", "whatsapp" to "", "telegram" to "")
hardcoded values

2024-05-12 10:06 UTC, Kuriv2001 commented
Theres is now a SocialMedia data class that can store different social medias with their group links. There is also a supported social media list in there, the only thing that need to be changed now, if a new social media will be supported.

The rest of the code now dynamically takes these values and nothing is hardcoded anymore.

2024-05-12 10:30 UTC, Kuriv2001 commented
ViewDetailsEventScreen doesn't update directly. Fixed with with Launched Effect

2024-05-12 15:13 UTC, QuicheLorraine3600 approved these changes
Amazing, please solve your conflicts and run tests before merging :)

2024-05-12 16:11 UTC, merged