Fixed issue multiple links discord
Chimpagne/ChimpagneApp pull request #209
Opened 2024-05-18 16:29 UTC by Kuriv2001

2024-05-21 14:56 UTC, leagrieder requested changes
Good PR. Good size and good job correcting this security issue.

Almost everything looks good to me, however there is one thing that I find strange.. If I enter invalid links or other things in the social event rectangles I am allowed to modify/create the event. I think it might make more sense to not allow event creation if what is written somewhere is not correct right? I believe that even though it the event seems to be saved with those bad modifications you have correctly coded things such that it doesn't actually save the new invalid social media links but I still feel like it would be more user friendly to add a toast message if something that is entered is invalid. Let me know what you think.

2024-05-22 16:25 UTC, Kuriv2001 commented
> Good PR. Good size and good job correcting this security issue.
> 
> Almost everything looks good to me, however there is one thing that I find strange.. If I enter invalid links or other things in the social event rectangles I am allowed to modify/create the event. I think it might make more sense to not allow event creation if what is written somewhere is not correct right? I believe that even though it the event seems to be saved with those bad modifications you have correctly coded things such that it doesn't actually save the new invalid social media links but I still feel like it would be more user friendly to add a toast message if something that is entered is invalid. Let me know what you think.

Hey, Thank you for your thoughts. It does make a lot of sense and i changed everything now, such that you can't create the event if the social media links are not correct.

I also added all the logic to editEventScreen (also for title and dates) as this has not yet been thought of

2024-05-22 21:15 UTC, leagrieder approved these changes

2024-05-22 21:15 UTC, leagrieder commented
Looks good now!! I approve this

2024-05-23 08:35 UTC, Athanaze approved these changes

2024-05-23 08:35 UTC, Athanaze commented on app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt
> +        for ((platform) in socialMediaStates) {
useless () around platform

2024-05-23 08:36 UTC, merged