Account screens refactor
Chimpagne/ChimpagneApp pull request #211
Opened 2024-05-19 11:56 UTC by QuicheLorraine3600

The account related screens had messy navigation, making them hard to incorporate with our future bottom navbar which will follow this paradigm: https://developer.android.com/develop/ui/compose/navigation#navigate-from-Compose.
I took the opportunity to refactor all those screens as they were inconsistent with the rest of the app in terms of translation and UI.

- I moved all account related UI classes to the `ui.account` package
- I merge the `AccountCreation`, `AccountEdition` screens into a single one. I also removed the `AccountChangeBody` method (which was taking 17 parameters)
- I removed the `ProfileImage` component as we already have the `ProfileIcon` one. I had to make some small modifications to `ProfileIcon` to make it clickable or not.
- I added all the missing translations, those screens were designed before we used string resources, so a lot were missing.
- I removed the `location` field from `ChimpagneAccount`, the view model and the screens following our team decision on it
- I added a new variation of the `GoBackButton` that takes a callback instead of a navController, please use this one to be compliant with the previously cited paradigm.

2024-05-19 14:21 UTC, Athanaze commented on app/src/main/java/com/monkeyteam/chimpagne/ui/account/AccountUpdateScreen.kt
> +            if (uri != null) {
instead of checking != null and else {} later, check if == null and else{}

2024-05-19 14:21 UTC, Athanaze commented on app/src/main/java/com/monkeyteam/chimpagne/ui/account/AccountUpdateScreen.kt
> +  return if (account.firstName == "") {
use .isEmpty()

2024-05-19 14:21 UTC, Athanaze commented on app/src/main/java/com/monkeyteam/chimpagne/ui/account/AccountUpdateScreen.kt
> +  } else if (account.lastName == "") {
use .isEmpty()

2024-05-19 14:21 UTC, Athanaze commented on app/src/main/java/com/monkeyteam/chimpagne/ui/components/Button.kt
> +@Deprecated(
Nice documentation, it will be useful when refactoring to follow the new paradigm

2024-05-19 14:21 UTC, Athanaze commented on app/src/main/java/com/monkeyteam/chimpagne/ui/account/AccountSettingsScreen.kt
> +        TopAppBar(
I believe we should start thinking about a ChimpagneTopBar component, currently the look of the top bar is not consistent throughout the app.

2024-05-20 08:03 UTC, Kuriv2001 requested changes
Well done! The overall refactoring looks really well done. This will help us maintain the code better in the future. It makes the code much easier to read and expand.

I really like the refactoring of the AccountBody, as when I created it in the beginning of the project, I didn't take the maintainability and complexity of it into account.

The removal of the location from the accountUpdateScreen and now using the new feature of @Athanaze, will make the experience of the user more seemless.

To change:
There is still the problem with the profile icon on the home screen. Nothing tells us that when we click it, it will lead us to the account settings (implement figma changes). Same for changing the profile picture in the updateAccountScreen, some small edit icon could be put on the the edge of the icon, to make this clearer.

 I also made one small comment in the code.

2024-05-20 20:34 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/account/AccountUpdateScreen.kt
> +  return if (account.firstName == "") {
very strange way to deal with strings

2024-05-20 20:37 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/account/AccountUpdateScreen.kt
> +                          if (editMode) R.string.account_edit_screen_title
oups, I forgot to set to use account_creation_screen_title

2024-05-21 07:51 UTC, Kuriv2001 commented
Alright, seems fine now, I will accept the PR.

2024-05-21 07:51 UTC, Kuriv2001 approved these changes

2024-05-23 08:30 UTC, Athanaze approved these changes

2024-05-23 08:30 UTC, merged