Weather UI For Event Screen
Chimpagne/ChimpagneApp pull request #231
Opened 2024-05-23 14:40 UTC by arnaudlvq

###

2024-05-23 14:41 UTC, arnaudlvq commented
https://github.com/Chimpagne/ChimpagneApp/assets/24866530/9109be18-05fc-4bac-8652-3144a3cd6657

2024-05-23 18:05 UTC, Athanaze approved these changes

2024-05-23 18:05 UTC, Athanaze commented on app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/WeatherCarousel.kt
> +                              "Temp : ${weather.temperatureLow}°C -> ${weather.temperatureHigh}°C",
a bit hacky but acceptable, since it's the same in french and english 😉

2024-05-23 18:05 UTC, Athanaze commented on app/src/main/res/values/strings.xml
> +    <string name="noforecast_alreadyoccured">Event has already occurred, no weather forecast :)</string>
Fun touch :)

2024-05-24 09:25 UTC, Kuriv2001 requested changes
Well done! This will help users whether they should pack an umbrella or not and how to dress accordingly.

I tested all the possible cases you mentioned (past event, current event and far in the future event) with a location specified and they all seem to work perfectly.

I found a little edge case that you didn't consider. When there is no location set, then the weather says: "Failed to fetch weather data". You should either return an error message, that no location has been selected or make it mandatory to select a location for the event. This should be fixed in one of those ways.

After that, the PR can be approved.

2024-05-24 16:01 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/WeatherCarousel.kt
> +                message = "Failed to fetch weather data."
not translated

2024-05-24 16:04 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/WeatherCarousel.kt
> +fun TextMessage(message: String?) {
Is it really useful to create a component inside another one ? It is used only one time

2024-05-24 16:06 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/WeatherCarousel.kt
> +fun WeatherCarousel(weatherData: List<Weather>) {
It is unclear if an external screen should use WeatherApp of WeatherCarousel

2024-05-24 16:09 UTC, QuicheLorraine3600 commented on app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/WeatherCarouselTest.kt
> +            startsAtTimestamp = buildTimestamp(9, 5, 2025, 15, 15),
will this test pass in the future ?

2024-05-26 09:41 UTC, Kuriv2001 commented
I agree with the comment of @QuicheLorraine3600 and created an issue for this task: #243. The PR is therefore approved.

2024-05-26 09:41 UTC, Kuriv2001 approved these changes

2024-05-28 23:20 UTC, QuicheLorraine3600 commented
Do not merge this PR, it breaks the tests

2024-05-29 07:41 UTC, QuicheLorraine3600 requested changes
please remove offline mode related things for this PR

2024-05-29 07:41 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/ChimpagneApplication.kt
> +class ChimpagneApplication : Application() {
not part of this PR

2024-05-29 07:41 UTC, QuicheLorraine3600 commented on app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt
> +                { exception ->
not part of this PR

2024-05-29 13:40 UTC, closed without merging